CREATE TABLE `hotels` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `hotel_name` varchar(255) NOT NULL,
  `hotel_location` varchar(255) NOT NULL,
  `hotel_description` varchar(255) NOT NULL,
  `hotel_host_number` int(11) NOT NULL,
  `hotel_rooms` int(11) NOT NULL,
  `hot_water` tinyint(1) NOT NULL,
  `heating` tinyint(1) NOT NULL,
  `internet` tinyint(1) NOT NULL,
  `air_condition` tinyint(1) NOT NULL,
  `closet` tinyint(1) NOT NULL,
  `tv` tinyint(1) NOT NULL,
  `garden` tinyint(1) NOT NULL,
  `car_parking` tinyint(1) NOT NULL,
  `type` enum('Guesthouse', 'Cottage', 'Hotel') NOT NULL,
  `currency` enum('USD','GEL','GBP','EUR') NOT NULL,
  `view` varchar(255) NOT NULL,
  `pet_friendly` tinyint(1) NOT NULL,
  `available_time` varchar(255) NOT NULL,
  `price_daily` varchar(255) NOT NULL,
  `price_monthly` varchar(255) DEFAULT NULL,
  `discount` int(11) DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '0',
  `success` enum('Pending', 'Success', 'Rejected') NOT NULL DEFAULT 'Pending',
  `user_id` bigint unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `hotels_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
